/**
 * Trip Planner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * This element describes timestamps for a service alert.
 */
export interface AdditionalInfoResponseTimestamps { 
    /**
     * A timestamp in `YYYY-MM-DDTHH:MM:SSZ` format that indicates when the alert was created.
     */
    creation?: string;
    /**
     * A timestamp in `YYYY-MM-DDTHH:MM:SSZ` format that indicates when the alert was last modified.
     */
    lastModification?: string;
    /**
     * This describes when the alert should published. Note that this is used as guidance only and your own needs may vary. 
     */
    availability?: any;
    /**
     * This describes when the incident is actually occurring. 
     */
    validity?: Array<any>;
}