/**
 * Trip Planner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RouteProduct } from './routeProduct';

/**
 * This element describes a single route that is affected by a service alert.
 */
export interface AdditionalInfoResponseAffectedLine { 
    /**
     * This is the unique ID that identifies the given line.
     */
    id?: string;
    /**
     * This element describes the destination of trips fulfilled by the given line.
     */
    destination?: any;
    /**
     * This is the full name of the route.
     */
    name?: string;
    /**
     * This is the short name or code of the route.
     */
    number?: string;
    product?: RouteProduct;
}