/**
 * Trip Planner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ParentLocation } from './parentLocation';

/**
 * This element describes a single stop that is affected by a service alert.
 */
export interface AdditionalInfoResponseAffectedStop { 
    /**
     * This the unique ID of the stop that is affected. It is the same ID that is used elsewhere in the system, such as in `XML_TRIP_REQUEST2` or `XML_STOPFINDER_REQUEST`.  
     */
    id?: string;
    /**
     * This is the title of the affected stop.
     */
    name?: string;
    /**
     * The type of the location that is affected.
     */
    type?: AdditionalInfoResponseAffectedStop.TypeEnum;
    parent?: ParentLocation;
}
export namespace AdditionalInfoResponseAffectedStop {
    export type TypeEnum = 'poi' | 'singlehouse' | 'stop' | 'platform' | 'street' | 'locality' | 'location' | 'gisPoint' | 'unknown';
    export const TypeEnum = {
        Poi: 'poi' as TypeEnum,
        Singlehouse: 'singlehouse' as TypeEnum,
        Stop: 'stop' as TypeEnum,
        Platform: 'platform' as TypeEnum,
        Street: 'street' as TypeEnum,
        Locality: 'locality' as TypeEnum,
        Location: 'location' as TypeEnum,
        GisPoint: 'gisPoint' as TypeEnum,
        Unknown: 'unknown' as TypeEnum
    };
}