/**
 * Trip Planner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CoordRequestResponseLocation } from './coordRequestResponseLocation';
import { ErrorResponse } from './errorResponse';

/**
 * This is the response data returned when performing an XSLT_COORD_REQUEST request. 
 */
export interface CoordRequestResponse { 
    /**
     * The version of the API that provided the response. Note that if this value is different to above, then the returned data may be different than expected. You can set the expected version using the `version` request parameter.  
     */
    version?: string;
    error?: ErrorResponse;
    /**
     * This contains a list of all of the stops, reload points and places of interest found based on the given request. 
     */
    locations?: Array<CoordRequestResponseLocation>;
}