/**
 * Trip Planner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DepartureMonitorResponseStopEvent } from './departureMonitorResponseStopEvent';
import { ErrorResponse } from './errorResponse';
import { StopFinderLocation } from './stopFinderLocation';

/**
 * This is the response data returned when performing an XML_DM_REQUEST request. 
 */
export interface DepartureMonitorResponse { 
    /**
     * The version of the API that provided the response. Note that if this value is different to above, then the returned data may be different than expected. You can set the expected version using the `version` request parameter.  
     */
    version?: string;
    error?: ErrorResponse;
    /**
     * Contains a list of stops that were matched based on the supplied `type_dm` and `name_dm` request values. There must be exactly one location present for the `stopEvents` response data to be populated. Additionally, the `mode` request value must be set to `direct`. 
     */
    location?: Array<StopFinderLocation>;
    /**
     * Contains a list of departures/arrivals for the stop included in the `location` property of the response. 
     */
    stopEvents?: Array<DepartureMonitorResponseStopEvent>;
}