/**
 * Trip Planner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * This element contains information about an error that may have occurred when handling an API request. 
 */
export interface ErrorResponse { 
    /**
     * Describes the error that went wrong
     */
    message?: string;
    /**
     * If the error was related to the API version, this element contains version information. 
     */
    versions?: any;
}