/**
 * Trip Planner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * This element describes a single message that may be included with an `XML_TRIP_REQUEST2` request.
 */
export interface TripRequestResponseMessage { 
    /**
     * Indicates the type of system message.
     */
    type?: string;
    /**
     * Indicates the server module that provided this system message.
     */
    module?: string;
    /**
     * This is an error/warning code for the message.
     */
    code?: number;
    /**
     * This is the text detail for the given message.
     */
    text?: string;
}