/**
 * Trip Planner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdditionalInfoResponseTimestamps } from './additionalInfoResponseTimestamps';

/**
 * This element describes a single information message that may be associated with a journey leg. The data in this is similar to that from `XML_ADDINFO_REQUEST`, but is presented differently. 
 */
export interface TripRequestResponseJourneyLegStopInfo { 
    timestamps?: AdditionalInfoResponseTimestamps;
    /**
     * This value indicates how important the service alert is. A value of `high` or `veryHigh` likely indicates that the alert will correspond to an event that impacts the ability to travel for relevant users, while `low` or `veryLow` might be more of an informational message. 
     */
    priority?: TripRequestResponseJourneyLegStopInfo.PriorityEnum;
    /**
     * This is a unique identifier for this particular service alert. Note that this same ID is used in XML_ADDINFO_REQUEST for the same alert. 
     */
    id?: string;
    /**
     * This number indicates the version of this alert. Initially when it is created it has version `1`, but if it is then updated it will have a new `lastModification` value and the version will now be `2`. 
     */
    version?: number;
    /**
     * This field contains a title that can be used when displaying the `url` URL. This value is equivalent to the `infoLinkText` value in `XML_ADDINFO_REQUEST`.  
     */
    urlText?: string;
    /**
     * This field contains a URL that contains additional information about the alert. This value is equivalent to the `infoLinkURL` value in `XML_ADDINFO_REQUEST`. 
     */
    url?: string;
    /**
     * This is the descriptive alert content. It may contain HTML tags and/or HTML entities. 
     */
    content?: string;
    /**
     * This is short summary that can be used as a heading for the alert content. It may contain HTML tags and/or HTML entities. 
     */
    subtitle?: string;
}
export namespace TripRequestResponseJourneyLegStopInfo {
    export type PriorityEnum = 'veryLow' | 'low' | 'normal' | 'high' | 'veryHigh';
    export const PriorityEnum = {
        VeryLow: 'veryLow' as PriorityEnum,
        Low: 'low' as PriorityEnum,
        Normal: 'normal' as PriorityEnum,
        High: 'high' as PriorityEnum,
        VeryHigh: 'veryHigh' as PriorityEnum
    };
}