/**
 * Trip Planner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ErrorResponse } from './errorResponse';
import { TripRequestResponseJourney } from './tripRequestResponseJourney';

/**
 * This element contains the response from an XML_TRIP_REQUEST2 request.
 */
export interface TripRequestResponse { 
    /**
     * The version of the API that provided the response. Note that if this value is different to above, then the returned data may be different than expected. You can set the expected version using the `version` request parameter.  
     */
    version?: string;
    error?: ErrorResponse;
    /**
     * Includes system messages that may be relevant to this particular request.
     */
    systemMessages?: any;
    /**
     * Contains zero or more journeys found based on the input parameters.
     */
    journeys?: Array<TripRequestResponseJourney>;
}