/**
 * Trip Planner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes a single download available for this journey stop.
 */
export interface TripRequestResponseJourneyLegStopDownload { 
    /**
     * This indicates what type of download this is. For example, `RM` refers to Route Map. 
     */
    type?: string;
    /**
     * This is the URL for the download. 
     */
    href?: string;
}