/**
 * Trip Planner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * This element describes a starting or finishing point for a walking instruction.
 */
export interface TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation { 
    /**
     * This includes information about the location in which this instruction takes place. 
     */
    location?: any;
    /**
     * XXX
     */
    area?: number;
    /**
     * If available, this is a platform number that relates to this instruction. It defaults to `0` if there is no such information available. 
     */
    platform?: number;
    /**
     * This is an identifier for this particular instruction / location, based on its location. 
     */
    georef?: string;
}