/**
 * Trip Planner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Not currently used.
 */
export interface TripRequestResponseJourneyFareZone { 
    /**
     * Not currently used.
     */
    net?: string;
    /**
     * Not currently used.
     */
    toLeg?: number;
    /**
     * Not currently used.
     */
    fromLeg?: number;
    /**
     * Not currently used.
     */
    neutralZone?: string;
}