/**
 * Trip Planner
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation } from './tripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation';

/**
 * The element describes a single walking instruction.
 */
export interface TripRequestResponseJourneyLegStopFootpathInfoFootpathElem { 
    /**
     * Contains additional information about this instruction, but is generally unused. 
     */
    description?: string;
    /**
     * This indicates the type of \"terrain\" for this instruction. `LEVEL` indicates a normal flat surface. 
     */
    type?: TripRequestResponseJourneyLegStopFootpathInfoFootpathElem.TypeEnum;
    /**
     * Indicates the floor number the instruction is starting from. If the `type` is `LEVEL`, then the `levelFrom` and `levelTo` values should be the same. 
     */
    levelFrom?: number;
    /**
     * Indicates the floor number the instruction ends of. If the `type` is `LEVEL`, then the `levelFrom` and `levelTo` values should be the same. 
     */
    levelTo?: number;
    /**
     * Indicates the direction of travel for this instruction. Generally a ramp, escalator or stairs will go `UP` or `DOWN` to a different floor. This value will be `LEVEL` when the `type` field is also `LEVEL`. 
     */
    level?: TripRequestResponseJourneyLegStopFootpathInfoFootpathElem.LevelEnum;
    origin?: TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation;
    destination?: TripRequestResponseJourneyLegStopFootpathInfoFootpathElemLocation;
}
export namespace TripRequestResponseJourneyLegStopFootpathInfoFootpathElem {
    export type TypeEnum = 'ESCALATOR' | 'ELEVATOR' | 'STAIRS' | 'LEVEL' | 'RAMP';
    export const TypeEnum = {
        ESCALATOR: 'ESCALATOR' as TypeEnum,
        ELEVATOR: 'ELEVATOR' as TypeEnum,
        STAIRS: 'STAIRS' as TypeEnum,
        LEVEL: 'LEVEL' as TypeEnum,
        RAMP: 'RAMP' as TypeEnum
    };
    export type LevelEnum = 'DOWN' | 'LEVEL' | 'UP';
    export const LevelEnum = {
        DOWN: 'DOWN' as LevelEnum,
        LEVEL: 'LEVEL' as LevelEnum,
        UP: 'UP' as LevelEnum
    };
}